### ISSUE TITLE
ModuleNotFoundError in authentik-migrate

### ISSUE THREAD

**Issue by Defelo** [nix-community/authentik-nix#19]
After updating from 2023.10.7 (https://github.com/nix-community/authentik-nix/commit/497c207488ad72ab55dc9912bda055cbeed47a92) to 2024.2.1 (https://github.com/nix-community/authentik-nix/commit/5ed5c481f2313ef4f92cae8c5fde07558e23351c), the `authentik-migrate.service` unit always fails with a `ModuleNotFoundError: No module named 'https'` error.

```
Starting authentik-migrate.service...
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620785.7511833, "file": "/nix/store/mgkg473cmqr16nrvyc2v8p7pa94y54n1-patched-authentik-source/authentik/lib/default.yml"}
{"event": "Loaded config", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620785.7539692, "file": "/etc/authentik/config.yml"}
{"event": "Loaded environment variables", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620785.7544122, "count": 2}
{"event": "'geoip' has been deprecated in favor of 'events.context_processors.geoip'! Please update your configuration.", "level": "warning", "logger": "authentik.lib.config", "timestamp": 1708620785.7545652}
2024-02-22 16:53:05 [info     ] applying django migrations
2024-02-22 16:53:05 [info     ] waiting to acquire database lock
{"event": "Booting authentik", "level": "info", "logger": "authentik.lib.config", "timestamp": 1708620787.3687036, "version": "2024.2.1"}
{"event": "Enabled authentik enterprise", "level": "info", "logger": "authentik.lib.config", "timestamp": 1708620787.3718634}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.373902, "path": "authentik.enterprise.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.3756738, "path": "authentik.blueprints.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.3779182, "path": "authentik.sources.plex.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.3801024, "path": "authentik.events.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.383519, "path": "authentik.admin.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.3864114, "path": "authentik.sources.ldap.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.3878176, "path": "authentik.stages.authenticator_totp.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.3919442, "path": "authentik.sources.oauth.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.3948407, "path": "authentik.policies.reputation.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.3983665, "path": "authentik.outposts.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.399911, "path": "authentik.enterprise.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.40456, "path": "authentik.providers.scim.settings"}
{"event": "Loaded app settings", "level": "debug", "logger": "authentik.lib.config", "timestamp": 1708620787.4062092, "path": "authentik.crypto.settings"}
{"domain_url": null, "event": "Failed to load MMDB database", "exc": "FileNotFoundError(2, 'No such file or directory')", "level": "warning", "logger": "authentik.events.context_processors.mmdb", "path": "/geoip/GeoLite2-ASN.mmdb", "pid": 46355, "schema_name": "public", "timestamp": "2024-02-22T16:53:08.123038"}
{"domain_url": null, "event": "Loaded MMDB database", "file": "/nix/store/c3bynnmjcs51lykq58d620yrf1ci19ni-geoip/GeoLite2-City.mmdb", "last_write": 1.0, "level": "info", "logger": "authentik.events.context_processors.mmdb", "pid": 46355, "schema_name": "public", "timestamp": "2024-02-22T16:53:08.129146"}
{"app_name": "authentik.tenants", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.tenants.checks", "pid": 46355, "schema_name": "public", "timestamp": "2024-02-22T16:53:08.485095"}
/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/django/db/backends/utils.py:98: RuntimeWarning: Accessing the database during app initialization is discouraged. To fix this warning, avoid executing queries in AppConfig.ready() or when your app modules are imported.
  warnings.warn(self.APPS_NOT_READY_WARNING_MSG, category=RuntimeWarning)
{"app_name": "authentik.admin", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.admin.tasks", "pid": 46355, "schema_name": "public", "timestamp": "2024-02-22T16:53:08.563663"}
{"app_name": "authentik.admin", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.admin.signals", "pid": 46355, "schema_name": "public", "timestamp": "2024-02-22T16:53:08.564606"}
{"app_name": "authentik.crypto", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.crypto.tasks", "pid": 46355, "schema_name": "public", "timestamp": "2024-02-22T16:53:08.568064"}
{"app_name": "authentik.flows", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.flows.signals", "pid": 46355, "schema_name": "public", "timestamp": "2024-02-22T16:53:10.927531"}
{"app_name": "authentik.outposts", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.outposts.tasks", "pid": 46355, "schema_name": "public", "timestamp": "2024-02-22T16:53:11.006541"}
{"app_name": "authentik.outposts", "domain_url": null, "event": "Imported related module", "level": "info", "logger": "authentik.blueprints.apps", "module": "authentik.outposts.signals", "pid": 46355, "schema_name": "public", "timestamp": "2024-02-22T16:53:11.007603"}
Traceback (most recent call last):
  File "/nix/store/4llq87n308rra4bcccmzn7pq95nb9qfq-authentik-migrate.py/bin/.migrate.py-wrapped", line 112, in <module>
    execute_from_command_line(["", "migrate_schemas"])
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/django/apps/registry.py", line 124, in populate
    app_config.ready()
  File "/nix/store/yag32v0bhmh1jbnawbrwvfvp96kkw3q5-authentik-static-workdir-deps/authentik/blueprints/apps.py", line 26, in ready
    self.reconcile_tenant()
  File "/nix/store/yag32v0bhmh1jbnawbrwvfvp96kkw3q5-authentik-static-workdir-deps/authentik/blueprints/apps.py", line 75, in reconcile_tenant
    self._reconcile(self.RECONCILE_TENANT_PREFIX)
  File "/nix/store/yag32v0bhmh1jbnawbrwvfvp96kkw3q5-authentik-static-workdir-deps/authentik/blueprints/apps.py", line 59, in _reconcile
    meth()
  File "/nix/store/yag32v0bhmh1jbnawbrwvfvp96kkw3q5-authentik-static-workdir-deps/authentik/outposts/apps.py", line 47, in reconcile_tenant_embedded_outpost
    outpost, updated = Outpost.objects.update_or_create(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/django/db/models/query.py", line 1009, in update_or_create
    obj.save(using=self.db, update_fields=update_fields)
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/django/db/models/base.py", line 924, in save_base
    post_save.send(
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/yag32v0bhmh1jbnawbrwvfvp96kkw3q5-authentik-static-workdir-deps/authentik/outposts/signals.py", line 67, in post_save_update
    outpost_post_save.delay(class_to_path(instance.__class__), instance.pk)
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/celery/app/task.py", line 594, in apply_async
    return app.send_task(
           ^^^^^^^^^^^^^^
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/tenant_schemas_celery/app.py", line 97, in send_task
    return super(CeleryApp, self).send_task(name, args=args, kwargs=kwargs, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/celery/app/base.py", line 798, in send_task
    self.backend.on_task_call(P, task_id)
    ^^^^^^^^^^^^
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/celery/app/base.py", line 1301, in backend
    self._backend = self._get_backend()
                    ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/celery/app/base.py", line 966, in _get_backend
    backend, url = backends.by_url(
                   ^^^^^^^^^^^^^^^^
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/celery/app/backends.py", line 68, in by_url
    return by_name(backend, loader), url
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/celery/app/backends.py", line 48, in by_name
    cls = symbol_by_name(backend, aliases)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/kfwha19i10v2lckc369j0bz93532vg9a-python3-3.11.6-env/lib/python3.11/site-packages/kombu/utils/imports.py", line 59, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/p1zbyfrpj3hq50mxh5hmxl3kqpa2b1am-python3-3.11.6/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'https'
authentik-migrate.service: Main process exited, code=exited, status=1/FAILURE
authentik-migrate.service: Failed with result 'exit-code'.
Failed to start authentik-migrate.service.
authentik-migrate.service: Consumed 4.993s CPU time, received 395B IP traffic, sent 735B IP traffic.
```

**Comment by WilliButz** [comment]
I'm unable to reproduce this issue myself and also did not hear from anyone else experiencing this. I suspect that this might be caused by flake input overrides. Could you provide the output section related to `authentik-nix` from the command `nix flake metadata` for your flake?

**Comment by Defelo** [comment]
Hi, I've just tried updating again using the latest commit, and unfortunately this problem still occurs. Interestingly this only seems to happen if the `authentik-migrate.service` is *restarted*, the first run of this service after updating seems to run fine. However, even if the migrate service is only run once and is in the `active (exited)` state, the `authentik-worker.service` now fails to start, also due to the same `ModuleNotFoundError`.

Relevant output of `nix flake metadata`:
```
├───authentik-nix: github:nix-community/authentik-nix/1392167355edc901975cfd9ab92e5501fcb6b2ff
│   ├───authentik-src: github:goauthentik/authentik/8256f1897df0a741a81dcb066d4edae879c30408
│   ├───flake-compat: github:edolstra/flake-compat/0f9255e01c2351cc7d116c072cb317785dd33b33
│   ├───flake-parts: github:hercules-ci/flake-parts/07f6395285469419cf9d078f59b5b49993198c00
│   │   └───nixpkgs-lib: github:NixOS/nixpkgs/b0d36bd0a420ecee3bc916c91886caca87c894e9?dir=lib
│   ├───flake-utils: github:numtide/flake-utils/1ef2e671c3b0c19053962c07dbda38332dcebf26
│   │   └───systems: github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e
│   ├───napalm: github:nix-community/napalm/edcb26c266ca37c9521f6a97f33234633cbec186
│   │   ├───flake-utils follows input 'authentik-nix/flake-utils'
│   │   └───nixpkgs follows input 'authentik-nix/nixpkgs'
│   ├───nixpkgs: github:NixOS/nixpkgs/56911ef3403a9318b7621ce745f5452fb9ef6867
│   ├───nixpkgs-23-05: github:NixOS/nixpkgs/70bdadeb94ffc8806c0570eb5c2695ad29f0e421
│   └───poetry2nix: github:nix-community/poetry2nix/403d923ea8e2e6cedce3a0f04a9394c4244cb806
│       ├───flake-utils follows input 'authentik-nix/flake-utils'
│       ├───nix-github-actions: github:nix-community/nix-github-actions/4bb5e752616262457bc7ca5882192a564c0472d2
│       │   └───nixpkgs follows input 'authentik-nix/poetry2nix/nixpkgs'
│       ├───nixpkgs follows input 'authentik-nix/nixpkgs'
│       ├───systems: github:nix-systems/default/da67096a3b9bf56a91d16901293e51ba5b49a27e
│       └───treefmt-nix: github:numtide/treefmt-nix/e82f32aa7f06bbbd56d7b12186d555223dc399d1
│           └───nixpkgs follows input 'authentik-nix/poetry2nix/nixpkgs'
```

**Comment by Defelo** [comment]
Ah, I think I found the problem. For some reason I had set the `services.authentik.settings.result_backend.url` option, which worked in the previous version, but seems to cause this error in the new version. After removing this option everything seems to work fine now, sorry for the confusion
